name: Ricardo Balk
description: Blog

collections:
  portfolio:
    output: true
    permalink: /:collection/:name

footer-links:
  source: "https://github.com/ellipticcurv3/personal-website"
  keybase: ellipticcurv3
  facebook: ellipticcurv3
  github: ellipticcurv3
  instagram: ellipticcurv3
  linkedin: ellipticcurv3
  twitter: ellipticcurv3
  stackoverflow: ellipticcurv3
  youtube: # channel/<your_long_string> or user/<user-name>

disqus: # Disqus shortname (not the username)
google_analytics: # e.g. UA-2110908-2

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://www.ricardobalk.nl

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

permalink: /blog/:categories/:title/

kramdown:
  input: GFM # Use GitHub flavored markdown, including triple backtick fenced code blocks
  syntax_highlighter: rouge # Jekyll 3 and GitHub Pages only support rouge
  syntax_highlighter_opts:
    css_class: 'highlight' # Use existing pygments syntax highlighting css

sass:
  style: :compressed # :compressed or non-minified using :expanded

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - _portfolio/TEMPLATE.md
  - .idea/
  - node_modules/
